### PR TITLE
Tons of Updates

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
[See changelog](https://github.com/rails-api/active_model_serializers/blob/91b37cee2c0815234d94214219497c0a26d33ffd/CHANGELOG.md)

### CODE REVIEW

**Comment by aaronlerch** [comment]
👍 looks good to me - just an update to the latest, right? I created this fork a while back to submit a PR - but keeping it up to date makes good sense too (if for no other reason, when we rely on git for a gem's source, we should do it out of the DT org and not someone else's who can delete it out from under us [which has happened]. Not that AMS is at risk of that, of course. Just on principle. :)

**Comment by NullVoxPopuli** [comment]
yeah, this is just an update. :-)

On my side project, I'm using AMS#master, so, I can vouch for it :-)

**Comment by NullVoxPopuli** [comment]
Does anyone use this repo? or do people use the rails-api one?

**Comment by NullVoxPopuli** [comment]
Closing, cause AMS is in disarray at the moment (ha).

I'd personally recommend http://jsonapi-rb.org/ (written by one of the AMS Owners).
I *think* AMS vNext is going to take a lot of inspiration from JSONAPI-rb.

But, I think JSONAPI-rb has more potential -- especially since it's broke up into smaller gems -- which makes writing native extensions _much_ easier. With the rust-ruby integration via Helix, I think JSONAPI-rb could eventually be _really_ fast. :-)

(Right now, JSONAPI-rb is only _slightly_ faster than AMS)

**Pull request closed without merging**
